name: Self Hosted Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: self-hosted

    steps:
      - name: Show hostname
        run: hostname

      - name: Show user
        run: whoami

      - name: Show OS
        run: uname -a

      - name: Hello
        run: echo "Hello from my AWS EC2!"